### ISSUE TITLE
error when run in a docker container

### ISSUE THREAD

**Issue by Magister-Machinis** [chamilad/pihole-restore#3]
Hello,
Thank you for creating this tool, I've tried integrating it into a docker container as a way to store/restore relevant configurations. When I try to run it however I get the below error. When run with the backtrace I get the noted expanded message. Commands included as well for reference. Any thoughts on what I could have missed would be appreciated.

command 

> RUN apt-get update && apt-get -y install wget && wget -O /backup/pihole_restore-v0.1.0-linux-x86_64 https://github.com/chamilad/pihole-restore/releases/download/v0.1.0/pihole_restore-v0.1.0-linux-x86_64 && chmod +x /backup/pihole_restore-v0.1.0-linux-x86_64 && /backup/pihole_restore-v0.1.0-linux-x86_64 -f /backup/pi-hole-localdns.tar.gz

error

> 12.49 [2024-04-07T22:14:16Z INFO  pihole_restore] start importing...
> 12.64 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a string", line: 1, column: 407)', src/pihole/gravity.rs:35:57
> 12.64 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error with backtrace

> 12.24 [2024-04-07T22:22:54Z INFO  pihole_restore] start importing...
> 12.39 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a string", line: 1, column: 407)', src/pihole/gravity.rs:35:57
> 12.39 stack backtrace:
> 12.42    0:     0x55c0b3d3810a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
> 12.42                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
> 12.42    1:     0x55c0b3d3810a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
> 12.42                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
> 12.42    2:     0x55c0b3d3810a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
> 12.42                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
> 12.42    3:     0x55c0b3d3810a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
> 12.42                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
> 12.43    4:     0x55c0b3d5c25f - core::fmt::write::h9ffde816c577717b
> 12.43                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
> 12.43    5:     0x55c0b3d35745 - std::io::Write::write_fmt::h88186074961638e4
> 12.43                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
> 12.43    6:     0x55c0b3d37ed5 - std::sys_common::backtrace::_print::h184198273ed08d59
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
> 12.44    7:     0x55c0b3d37ed5 - std::sys_common::backtrace::print::h1b4d8e7add699453
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
> 12.44    8:     0x55c0b3d3945e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
> 12.44    9:     0x55c0b3d39205 - std::panicking::default_hook::h48c64f31d8b3fd03
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
> 12.44   10:     0x55c0b3d399be - std::panicking::rust_panic_with_hook::hafdc493a79370062
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
> 12.44   11:     0x55c0b3d398b9 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
> 12.44   12:     0x55c0b3d38576 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
> 12.44   13:     0x55c0b3d39612 - rust_begin_unwind
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
> 12.44   14:     0x55c0b3bfc5e3 - core::panicking::panic_fmt::h0f6ef0178afce4f2
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
> 12.44   15:     0x55c0b3bfca93 - core::result::unwrap_failed::h8090202169109f9c
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
> 12.44   16:     0x55c0b3c1b846 - pihole_restore::pihole::gravity::restore_domainlist::hd24fc6415c5ce0ea
> 12.44   17:     0x55c0b3c16992 - pihole_restore::main::h8bddb4b36e5890f0
> 12.44   18:     0x55c0b3c0d533 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d05f45bf03629de
> 12.44   19:     0x55c0b3c0d629 - std::rt::lang_start::{{closure}}::h0753729e15fef3d4
> 12.44   20:     0x55c0b3d3084e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
> 12.44   21:     0x55c0b3d3084e - std::panicking::try::do_call::h4044173225fe83dd
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
> 12.44   22:     0x55c0b3d3084e - std::panicking::try::hd8a722c09d156a53
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
> 12.44   23:     0x55c0b3d3084e - std::panic::catch_unwind::hd2ca07971cf0119b
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
> 12.44   24:     0x55c0b3d3084e - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
> 12.44                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
> 12.45   25:     0x55c0b3d3084e - std::panicking::try::do_call::hf47aa1aa005e5f1a
> 12.45                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
> 12.45   26:     0x55c0b3d3084e - std::panicking::try::h73d246b2423eaf4e
> 12.45                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
> 12.45   27:     0x55c0b3d3084e - std::panic::catch_unwind::hbaaeae8f1b2f9915
> 12.45                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
> 12.45   28:     0x55c0b3d3084e - std::rt::lang_start_internal::h76f3e81e6b8f13f9
> 12.45                                at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
> 12.45   29:     0x55c0b3c19d35 - main
> 12.45   30:     0x7fe38dfd8d0a - __libc_start_main
> 12.45   31:     0x55c0b3bfcc2a - _start
> 12.45   32:                0x0 - <unknown>

Edit: formatting of the original post was a mess for some reason, should be a bit better now

**Comment by chamilad** [comment]
Sorry, I haven't been paying attention for this past month. I'll check this one out this week.

In the meantime, can you let me know the Docker base image you tried to use? specific tag would be really helpful.

**Comment by Magister-Machinis** [comment]
I have it set to latest, i think that would have been pihole/pihole:2024.03.2 when I posted this though.

**Comment by chamilad** [comment]
Sorry for the long turnaround for this!

I think I know a possible cause for this. I'll try and push a fix this weekend.

**Comment by chamilad** [comment]
reproduced
